import './style.css';
const DB={url:localStorage.getItem('ss_url')||'',key:localStorage.getItem('ss_key')||''};
const demo={
 user:{id:'demo-student',name:'Demo Student',role:'student'},
 courses:[{id:'js',title:'Modern JavaScript',category:'Programming',level:'Beginner',rating:4.8,students:128,description:'Build a strong JavaScript foundation through short videos, checks, coding practice and projects.',thumb:'https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&w=900&q=80',progress:38,lessons:16,completed:6}],
 lessons:[{id:1,title:'Variables & Data Types',module:'Module 1',duration:'12 min',video:'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',complete:true},{id:2,title:'Functions & Scope',module:'Module 1',duration:'15 min',video:'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',complete:true},{id:3,title:'Arrays & Objects',module:'Module 2',duration:'18 min',video:'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',complete:false},{id:4,title:'DOM Fundamentals',module:'Module 2',duration:'20 min',video:'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',complete:false}],
 questions:[{id:1,lesson_id:3,type:'mcq',question:'Which keyword creates a block-scoped variable?',options:['var','let','define','new'],answer:'let',explanation:'let is block scoped.'}],
 problems:[{id:1,title:'Sum an Array',difficulty:'Easy',statement:'Write a function that returns the sum of all numbers in an array.',starter:'function sum(arr) {\n  // your code\n}',tests:[{input:'[1,2,3]',expected:'6'},{input:'[5,5]',expected:'10'}]}]
};
let state={page:'home',course:null,lesson:3,user:demo.user,config:DB,toast:null};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(msg){state.toast=msg;render();setTimeout(()=>{state.toast=null;render()},2400)}
async function api(path,opts={}){try{const r=await fetch(path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});return await r.json()}catch(e){return {error:e.message}}}
async function sb(path,opts={}){if(!state.config.url||!state.config.key) return null;const r=await fetch(state.config.url+'/rest/v1/'+path,{...opts,headers:{apikey:state.config.key,Authorization:'Bearer '+state.config.key,'Content-Type':'application/json',Prefer:'return=representation',...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
function shell(content){return `<div class="app"><header><div class="brand" onclick="go('home')"><span class="mark">S</span><span>SkillStream</span></div><nav><button onclick="go('home')">Learn</button><button onclick="go('dashboard')">Dashboard</button><button onclick="go('analytics')">Analytics</button></nav><div class="header-right"><button class="icon" onclick="go('settings')">⚙</button><div class="avatar">${esc(state.user.name[0])}</div></div></header><main>${content}</main>${state.toast?`<div class="toast">${esc(state.toast)}</div>`:''}</div>`}
function go(p){state.page=p;render()}
function home(){return `<section class="hero"><div><div class="eyebrow">ACTIVE LEARNING PLATFORM</div><h1>Learn. Prove. <em>Master.</em></h1><p>SkillStream connects every lesson to questions and practical problems, so students build understanding before moving forward.</p><div class="actions"><button class="primary" onclick="openCourse()">Continue learning →</button><button class="secondary" onclick="go('catalog')">Explore courses</button></div></div><div class="hero-card"><div class="hero-stat"><strong>38%</strong><span>Course progress</span></div><div class="bar"><i style="width:38%"></i></div><div class="mini-row"><span>6 / 16 lessons</span><span>🔥 7 day streak</span></div></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">YOUR LEARNING</div><h2>Continue where you left off</h2></div><button class="text-btn" onclick="go('catalog')">View all courses →</button></div><div class="course-card" onclick="openCourse()"><img src="${demo.courses[0].thumb}"><div class="course-body"><span class="pill">${demo.courses[0].category}</span><h3>${demo.courses[0].title}</h3><p>${demo.courses[0].description}</p><div class="meta"><span>★ ${demo.courses[0].rating}</span><span>16 lessons</span><span>Beginner</span></div><div class="bar"><i style="width:38%"></i></div><small>38% complete · Continue with Arrays & Objects</small></div><div class="play">▶</div></div></section><section class="feature-grid"><article><b>01</b><h3>Video → Question</h3><p>Required watch percentage unlocks understanding checks.</p></article><article><b>02</b><h3>Question → Problem</h3><p>Prove the concept before the practical task becomes available.</p></article><article><b>03</b><h3>Problem → Mastery</h3><p>Code, submit, analyze mistakes and receive the next recommendation.</p></article></section>`}
function catalog(){return `<section class="page-head"><div class="eyebrow">COURSE CATALOG</div><h1>Choose what to learn</h1><p>Structured courses with progress-gated practice.</p></section><div class="filters"><input placeholder="Search courses…" oninput="filterCourses(this.value)"><select><option>All categories</option><option>Programming</option><option>Data</option></select><select><option>All levels</option><option>Beginner</option><option>Intermediate</option></select></div><div id="course-list">${courseList()}</div>`}
function courseList(){return demo.courses.map(c=>`<div class="catalog-card" onclick="openCourse()"><img src="${c.thumb}"><div><span class="pill">${c.category}</span><h3>${c.title}</h3><p>${c.description}</p><div class="meta"><span>★ ${c.rating}</span><span>${c.students} learners</span><span>${c.level}</span></div></div><button class="secondary">Open</button></div>`).join('')}
function filterCourses(v){$('#course-list').innerHTML=demo.courses.filter(c=>c.title.toLowerCase().includes(v.toLowerCase())).map(c=>`<div class="catalog-card"><img src="${c.thumb}"><div><span class="pill">${c.category}</span><h3>${c.title}</h3><p>${c.description}</p></div><button class="secondary" onclick="openCourse()">Open</button></div>`).join('')||'<div class="empty">No courses found.</div>'}
function openCourse(){state.course='js';state.page='course';render()}
function course(){return `<section class="course-banner"><div><span class="pill">Programming · Beginner</span><h1>Modern JavaScript</h1><p>Learn JavaScript fundamentals with guided videos, checks and coding practice.</p><div class="meta"><span>★ 4.8</span><span>16 lessons</span><span>128 learners</span></div></div><div class="course-progress"><strong>38%</strong><span>complete</span><div class="bar"><i style="width:38%"></i></div></div></section><div class="course-layout"><aside class="syllabus"><div class="aside-title">Course content <span>6 / 16</span></div>${['Module 1 · Foundations','Module 2 · Core JavaScript','Module 3 · Browser & DOM','Module 4 · Async JavaScript'].map((m,i)=>`<div class="module"><b>${m}</b><span>${i<1?'✓':'○'}</span>${i<2?demo.lessons.filter(x=>x.module==='Module '+(i+1)).map(l=>`<button class="lesson ${l.id===state.lesson?'active':''}" onclick="openLesson(${l.id})"><span>${l.complete?'✓':'○'}</span>${l.title}<small>${l.duration}</small></button>`).join(''): '<div class="locked">🔒 Complete previous module</div>'}</div>`).join('')}</aside><div class="lesson-area">${lessonView()}</div></div>`}
function openLesson(id){state.lesson=id;state.page='lesson';render()}
function lessonView(){const l=demo.lessons.find(x=>x.id===state.lesson)||demo.lessons[2];return `<div class="video-wrap"><video id="player" controls src="${l.video}" ontimeupdate="trackVideo(this)"></video><div class="video-overlay"><span>Lesson ${l.id}</span><span>Required completion: 80%</span></div></div><div class="lesson-title"><div><span class="eyebrow">${l.module}</span><h2>${l.title}</h2></div><button class="secondary" onclick="bookmark()">☆ Bookmark</button></div><div class="tabs"><button class="tab active">Overview</button><button class="tab">Notes</button><button class="tab">Discussion</button><button class="tab">AI Tutor</button></div><div class="learning-grid"><section><h3>Understanding check</h3><p class="muted">Watch at least 80% of this lesson to unlock the question.</p><div class="question-card"><span class="pill">Unlocked for demo</span><h3>Which keyword creates a block-scoped variable?</h3>${['var','let','define','new'].map(o=>`<button class="option" onclick="answer('${o}')">${o}</button>`).join('')}<div id="answer-result"></div></div></section><aside class="next-card"><div class="eyebrow">NEXT ACTIVITY</div><h3>Problem: Sum an Array</h3><p>Apply arrays and functions in a small coding challenge.</p><button class="primary" onclick="go('problem')">Open problem →</button></aside></div>`}
function trackVideo(v){localStorage.setItem('ss_video_'+state.lesson,Math.round(v.currentTime/v.duration*100)||0)}
function answer(o){$('#answer-result').innerHTML=o==='let'?'<div class="success">✓ Correct. Problem unlocked.</div>':'<div class="error">Not quite. Review block scope and try again.</div>';if(o==='let')demo.lessons.find(x=>x.id===state.lesson).complete=true}
function bookmark(){toast('Bookmark saved at this timestamp.')}
function problem(){return `<div class="problem-head"><div><span class="eyebrow">PRACTICE LAB</span><h1>Sum an Array</h1><p>Return the sum of every number in an array.</p></div><span class="difficulty">Easy</span></div><div class="problem-layout"><article class="problem-card"><h3>Problem statement</h3><p>Write a function <code>sum(arr)</code> that returns the total of all numeric values in the array.</p><h4>Examples</h4><pre>Input: [1, 2, 3]\nOutput: 6\n\nInput: [5, 5]\nOutput: 10</pre><h4>Concepts</h4><div class="tags"><span>Arrays</span><span>Functions</span><span>Loops</span></div></article><section class="editor-card"><div class="editor-top"><select id="lang"><option>JavaScript</option><option>Python</option><option>Java</option><option>C++</option></select><button class="secondary" onclick="runCode()">▶ Run</button><button class="primary" onclick="submitCode()">Submit</button></div><textarea id="code">function sum(arr) {\n  return arr.reduce((a, b) => a + b, 0);\n}</textarea><div id="code-result" class="console">Ready. Run sample tests before submitting.</div></section></div>`}
async function runCode(){const code=$('#code').value;const lang=$('#lang').value;$('#code-result').textContent='Running sample tests…';const r=await api('/api/code-run',{method:'POST',body:JSON.stringify({code,language:lang,tests:demo.problems[0].tests})});$('#code-result').textContent=r.output||r.error||'Execution completed.'}
function submitCode(){const code=$('#code').value;const good=/reduce|for\s*\(|while\s*\(/.test(code);$('#code-result').innerHTML=good?'<span class="success">✓ Accepted — all visible tests passed. Problem completed.</span>':'<span class="error">Tests failed. Add logic that calculates the array total.</span>';if(good)toast('Problem completed — next lesson unlocked.')}
function dashboard(){return `<section class="page-head"><div class="eyebrow">STUDENT DASHBOARD</div><h1>Good afternoon, ${esc(state.user.name)}.</h1><p>Here is your learning snapshot.</p></section><div class="stats"><div><strong>38%</strong><span>Course progress</span></div><div><strong>7</strong><span>Day streak</span></div><div><strong>84%</strong><span>Quiz average</span></div><div><strong>12</strong><span>Problems solved</span></div></div><div class="dashboard-grid"><section class="panel"><div class="section-head"><h2>Continue learning</h2><button class="text-btn" onclick="openCourse()">Open course →</button></div><div class="dash-course"><img src="${demo.courses[0].thumb}"><div><b>Modern JavaScript</b><p>Next: Arrays & Objects</p><div class="bar"><i style="width:38%"></i></div></div></div></section><section class="panel"><h2>Recommended for you</h2><div class="recommend"><span>↗</span><div><b>Practice: Array Methods</b><p>Based on your recent quiz performance</p></div></div><div class="recommend"><span>↗</span><div><b>Review: Scope & Closures</b><p>Strengthen a frequently missed concept</p></div></div></section></div>`}
function analytics(){return `<section class="page-head"><div class="eyebrow">LEARNING ANALYTICS</div><h1>Your progress, explained.</h1><p>SkillStream turns activity into practical learning insights.</p></section><div class="analytics-grid"><div class="panel"><h3>Concept strengths</h3><div class="metric"><span>Variables</span><b>92%</b><div class="bar"><i style="width:92%"></i></div></div><div class="metric"><span>Functions</span><b>84%</b><div class="bar"><i style="width:84%"></i></div></div><div class="metric"><span>Arrays</span><b>61%</b><div class="bar"><i style="width:61%"></i></div></div><div class="metric"><span>DOM</span><b>46%</b><div class="bar"><i style="width:46%"></i></div></div></div><div class="panel insight"><span class="insight-icon">✦</span><h3>AI learning insight</h3><p>You are progressing well with JavaScript fundamentals. Arrays and DOM concepts need more practice before attempting advanced topics.</p><button class="secondary" onclick="toast('Revision roadmap created.')">Create revision roadmap</button></div></div>`}
function settings(){return `<section class="page-head"><div class="eyebrow">SETUP</div><h1>Database connection</h1><p>Supabase is used for authentication, courses, progress, assessments and analytics.</p></section><div class="panel settings"><label>Supabase project URL<input id="sb-url" value="${esc(state.config.url)}" placeholder="https://xxxx.supabase.co"></label><label>Supabase anon key<input id="sb-key" value="${esc(state.config.key)}" placeholder="eyJhbGci..."></label><button class="primary" onclick="saveSettings()">Save connection</button><button class="secondary" onclick="testDb()">Test database</button><div id="db-status" class="muted"></div><hr><h3>Demo mode</h3><p>You can use the full learning flow immediately in demo mode. Once Supabase credentials are saved, production data can be loaded through the supplied schema.</p></div>`}
function saveSettings(){state.config.url=$('#sb-url').value.trim().replace(/\/$/,'');state.config.key=$('#sb-key').value.trim();localStorage.setItem('ss_url',state.config.url);localStorage.setItem('ss_key',state.config.key);toast('Database connection saved.');}
async function testDb(){const el=$('#db-status');el.textContent='Testing…';try{const r=await sb('courses?select=id&limit=1');el.textContent='✓ Supabase connection is working.'}catch(e){el.textContent='✕ Connection failed: '+e.message}}
function render(){let c=state.page==='home'?home():state.page==='catalog'?catalog():state.page==='course'?course():state.page==='lesson'?`<div class="back" onclick="go('course')">← Back to course</div>${lessonView()}`:state.page==='problem'?problem():state.page==='dashboard'?dashboard():state.page==='analytics'?analytics():settings();document.body.innerHTML=shell(c)}
window.go=go;window.openCourse=openCourse;window.openLesson=openLesson;window.answer=answer;window.bookmark=bookmark;window.runCode=runCode;window.submitCode=submitCode;window.saveSettings=saveSettings;window.testDb=testDb;window.trackVideo=trackVideo;window.filterCourses=filterCourses;render();
